// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Exercise struct {
	ID                  int32
	Name                string
	Description         sql.NullString
	Duration            sql.NullInt32
	Repetitions         sql.NullInt32
	Sets                sql.NullInt32
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	ExcludeFromCooldown sql.NullBool
}

type ExerciseGroup struct {
	ID          int32
	Name        string
	Description sql.NullString
}

type ExerciseGroupExercise struct {
	ExerciseID int32
	GroupID    int32
}

type ExerciseLevelMapping struct {
	ExerciseID int32
	LevelID    int32
}

type ExperienceLevel struct {
	ID          int32
	Name        string
	Description sql.NullString
}

type User struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Email             string
	Username          string
	PasswordHash      string
	ExperienceLevelID sql.NullInt32
}
