version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_NAME=fitted
      - DB_PORT=5432
      - SESSION_KEY=your-session-key  # For auth_middleware.go
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=fitted
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount migrations directory
      - ./sql/schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge